[window]
opacity = 0.99

[window.padding]
x = 5
y = 5

[window.dimensions]
columns = 210
lines = 30

[font]
size = 13.0

[general]
import = ["/home/enzo/.config/alacritty/themes/themes/carbonfox.toml"]
